# Site settings
title: "Sergio's Bernal resume"
description: "Welcome to my resume !"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Sergio Bernal"
resume_title:                   "Javascript Web Apps Development student"
resume_contact_email:           "sergioguillot@gmail.com"
resume_contact_telephone:       "+34 684 082 532"
resume_contact_address:         "Valencia, Spain"
#resume_header_contact_info:    ""
resume_header_intro: "<p>This is my markdown resume. I was born in 1995. I'm GitHub pages to host this static site. You might think that I'm a lazy guy but I tried to be optimal, lean and ingenious!</p>
<p>I'm learning to develop Web Apps and completely focused in JS programming, but also used to develop in PHP. I want to focus my professional career into Node.js and Javascript.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     true
resume_section_links:           true
resume_section_meetups:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/imsergiobernal"
  resume_twitter_url:           "https://twitter.com/imsergiobernal"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/sergio-bernal-guillot/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "https://sergiobernal.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
